name: secure ci pipeline

on:
 push:

jobs:
  build:
   runs-on: ubuntu-latest

 steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: initial dependencies
        run: pip install -r requirements.txt

      - name: build docker image
        run: docker build -t secure-app
