name: Security Pipeline

on:
  push:
    branches:
      - main

jobs:

  security-scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t secure-app .

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-app
          format: table
